name: First workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v1

      - name: hi
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"
